# Generated by Django 5.1.1 on 2024-11-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_image",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("followers", models.IntegerField(blank=True, null=True)),
                ("access_token", models.CharField(max_length=512)),
                ("refresh_token", models.CharField(max_length=512)),
                ("token_expiry", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecentlyPlayed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_name", models.CharField(max_length=255)),
                ("artist_name", models.CharField(max_length=255)),
                ("played_at", models.DateTimeField()),
                ("spotify_url", models.URLField(max_length=1024)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.spotifyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("spotify_url", models.URLField(max_length=1024)),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("genres", models.CharField(blank=True, max_length=512, null=True)),
                ("popularity", models.IntegerField()),
                ("rank", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.spotifyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("spotify_url", models.URLField(max_length=1024)),
                ("album_name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("artist_name", models.CharField(max_length=255)),
                ("duration_ms", models.IntegerField()),
                ("rank", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.spotifyprofile",
                    ),
                ),
            ],
        ),
    ]
