# Generated by Django 5.1.1 on 2024-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_spotifyprofile_recentlyplayed_topartist_toptrack"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyprofile",
            name="email",
            field=models.EmailField(default="unknown@example.com", max_length=254),
        ),
    ]
