# Generated by Django 5.1.1 on 2024-11-05 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_spotifyprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifyprofile",
            name="token_expiry",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
