# Generated by Django 5.1.1 on 2024-11-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_spotifyprofile_token_expiry"),
    ]

    operations = [
        migrations.RemoveField(model_name="spotifyprofile", name="profile_image",),
    ]
