# Generated by Django 5.1.1 on 2024-11-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_spotifyprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="topartist", name="user",),
        migrations.RemoveField(model_name="toptrack", name="user",),
        migrations.RemoveField(model_name="spotifyprofile", name="access_token",),
        migrations.RemoveField(model_name="spotifyprofile", name="display_name",),
        migrations.RemoveField(model_name="spotifyprofile", name="email",),
        migrations.RemoveField(model_name="spotifyprofile", name="followers",),
        migrations.RemoveField(model_name="spotifyprofile", name="refresh_token",),
        migrations.RemoveField(model_name="spotifyprofile", name="token_expiry",),
        migrations.AddField(
            model_name="spotifyprofile",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="RecentlyPlayed",),
        migrations.DeleteModel(name="TopArtist",),
        migrations.DeleteModel(name="TopTrack",),
    ]
