# Generated by Django 5.1.1 on 2024-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_topartist_user_remove_toptrack_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="SpotifyProfile",),
    ]
