# Generated by Django 5.1.1 on 2024-11-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_spotify_access_token_user_spotify_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_top_tracks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
