# Generated by Django 5.1.1 on 2024-11-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_spotify_top_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_top_tracks_long",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_top_tracks_medium",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_top_tracks_short",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
