# Generated by Django 5.1.1 on 2024-11-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0012_user_spotify_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
        migrations.AlterField(
            model_name="user",
            name="spotify_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["spotify_id"], name="users_user_spotify_44cc7f_idx"
            ),
        ),
    ]
