# Generated by Django 5.1.1 on 2024-11-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0013_alter_user_options_alter_user_spotify_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user", name="users_user_spotify_44cc7f_idx",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("spotify_id__isnull", False)),
                fields=("spotify_id",),
                name="unique_spotify_id",
            ),
        ),
    ]
