# Generated by Django 5.1.1 on 2024-11-18 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_user_users_user_spotify_44cc7f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wrapper_type",
                    models.CharField(
                        choices=[
                            ("RECENTLY_PLAYED", "Recently Played"),
                            ("TOP_TRACKS_SHORT", "Top Tracks Short Term"),
                            ("TOP_TRACKS_MEDIUM", "Top Tracks Medium Term"),
                            ("TOP_TRACKS_LONG", "Top Tracks Long Term"),
                            ("TOP_ARTISTS", "Top Artists"),
                            ("TOP_ALBUM", "Top Album"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("genres", models.JSONField(default=list)),
                ("popularity", models.IntegerField(default=0)),
                (
                    "spotify_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artists",
                        to="users.spotifydata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("total_tracks", models.IntegerField(default=0)),
                ("play_count", models.IntegerField(default=1)),
                (
                    "spotify_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="users.spotifydata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("popularity", models.IntegerField(default=0)),
                (
                    "spotify_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="users.spotifydata",
                    ),
                ),
            ],
        ),
    ]
