# Generated by Django 5.1.1 on 2024-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_genre_spotify_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifydata",
            name="wrapper_type",
            field=models.CharField(
                choices=[
                    ("RECENTLY_PLAYED", "Recently Played"),
                    ("TOP_TRACKS_SHORT", "Top Tracks Short Term"),
                    ("TOP_TRACKS_MEDIUM", "Top Tracks Medium Term"),
                    ("TOP_TRACKS_LONG", "Top Tracks Long Term"),
                    ("TOP_ARTISTS", "Top Artists"),
                    ("TOP_ALBUMS", "Top Albums"),
                    ("TOP_GENRES", "Top Genres"),
                    ("TOP_PLAYLISTS", "Top Playlists"),
                ],
                max_length=20,
            ),
        ),
    ]
