# Generated by Django 5.1.1 on 2024-12-01 20:51

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_duoinvite_duowrapped"),
    ]

    operations = [
        migrations.RemoveField(model_name="duoinvite", name="recipient_email",),
        migrations.AddField(
            model_name="duoinvite",
            name="recipient",
            field=models.ForeignKey(
                default=users.models.get_default_recipient,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
