# Generated by Django 5.1.1 on 2024-12-01 21:44

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_duoinvite_recipient_email_duoinvite_recipient"),
    ]

    operations = [
        migrations.RemoveField(model_name="duoinvite", name="token",),
        migrations.AddField(
            model_name="duoinvite",
            name="data",
            field=models.JSONField(default=users.models.get_default_data),
        ),
        migrations.DeleteModel(name="DuoWrapped",),
    ]
