# Generated by Django 5.1.1 on 2024-12-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_remove_duoinvite_token_duoinvite_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duoinvite",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
